### ISSUE TITLE
Data label upright on pie charts

### ISSUE THREAD

**Issue by aguilar1181** [ChartsCSS/charts.css#112]
is there a way to prevent the data label on the pie charts from rotating?

I have tried playing with the `.charts-css.pie tbody tr td .data` class however when I edit the rotate value all the labels merge instead of staying in their designated area.

![Screenshot 2023-11-07 at 00-01-38 The Powergrid – American Transmission Co](https://github.com/ChartsCSS/charts.css/assets/3482055/e5dbc4e4-54fc-4890-a3b3-f1fb7b4d31eb)

![Screenshot 2023-11-07 at 00-08-29 The Powergrid – American Transmission Co](https://github.com/ChartsCSS/charts.css/assets/3482055/72725161-de77-4a7c-8b93-e3dc9008d03a)

**Comment by ramiy** [comment]
Currently no, but I will start working on a solution. Meanwhile, if you find a good workaround to solve the issue, please share the code.

**Comment by freelimiter** [comment]
Looking for solution for this issue. Thank you!

**Comment by kapouer** [comment]
@ramiy starting point, though it still needs a lot of adjustments (like taking into account the size of the label)
```css
table.charts-css.pie > tbody > tr > td {
	--half: calc(pi * (var(--start) + var(--end)));
	--place: 0.98;

	padding-top: calc(50% * (1 - var(--place) * cos(var(--half))));
	padding-left: calc(50% * (1 + var(--place) * sin(var(--half))));
	white-space: nowrap;
}
```

**Comment by kapouer** [comment]
Correction: I found out there is css to position the labels when they are wrapped in tag with data class.
So the issue here is to make the text not be turned. This works:

```css
table.charts-css.pie > tbody > tr > td > .data {
	--angle: calc(0.5turn * var(--start, 0) + 0.5turn * var(--end, 0));
	--offset: calc(50% - 0.5em);

	transform:
		rotate(var(--angle))
		translateY(calc(-1 * var(--offset)))
		rotate(calc(-1 * var(--angle)))
		translateY(var(--offset));
	font-size:1em;
}
```
