### ISSUE TITLE
Feature: automatic heights

### ISSUE THREAD

**Issue by matt-spence-rokk** [ChartsCSS/charts.css#67]
One question that often pops up from a few developers I know:

> "how can we responsively size the charts?"

### 1. Non-responsive ❌

Simply define `height: 400px` on a `.charts-css` chart.

### 2. Responsive ⌛

There are a few ways of doing this, though it usually falls down the responsive way of:

1. Creating a wrapper div with:
```css
.charts-css-container {
    position: relative;
    padding-bottom: 125%;
}
```

2. Adding the following rules to the table:
```css
.charts-css {
    position: absolute;
    width: 100%;
    height: 100%;
}
```

Then play around with the `padding-bottom` rule to best scale the chart.

At the moment using `aspect-ratio` does work, though the support is not 100% there yet for all browsers.

## So, what to do?

These appear to be the obvious options:

- Offer default sizings: `charts-css-4/3`, `charts-css-16/9`
- Leave as a task for developers to worry about and update the docs to provide support with this

Please let me know what you think of these options or have your own idea - if you'd like support with the docs, I'd be happy to send a pull request. 👍
